{
 "title": "Notebook Controller SLIs",
 "tags": [
  "opendatahub",
  "notebooks",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "opendatahub" }
  ]
 },
 "panels": [
  { "title": "Availability SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Notebook Controller Availability",
   "type": "graph",
   "description": "What is the current availability status of the Notebook Controller leader pod",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{service=\"notebook-controller-service\",namespace=~\"$namespace\"})",
     "legendFormat": "Status (Kubeflow)"
    },
    {
     "expr": "sum(up{service=\"openshift-notebook-controller-service\",namespace=~\"$namespace\"})",
     "legendFormat": "Status (Openshift)"
    }
   ]
  },
  {
   "title": "Notebooks Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(notebook_running{namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(group(kube_pod_labels{label_notebook_name!=\"\"}) by (label_notebook_name, pod, namespace) * on(pod, namespace) group_right() (kube_pod_status_phase{phase=\"Running\"} == 1))",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Notebooks SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notebooks Running",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(group(kube_pod_labels{label_notebook_name!=\"\"}) by (label_notebook_name, pod, namespace) * on(pod, namespace) group_right() (kube_pod_status_phase{phase=\"Running\"} == 1)) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Notebooks Culling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(notebook_culling_total) by (exported_namespace)",
       "legendFormat": "{{exported_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notebook Controller Pod Restarts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() irate(kube_pod_container_status_restarts_total[5m]) * 20",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() irate(kube_pod_container_status_restarts_total[5m]) * 20",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Notebook Spawn Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(notebook_create_total) - sum(notebook_create_failed_total)) / sum(notebook_create_total) or (1 - (absent(notebook_create_total) or vector(0)))",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(notebook_create_failed_total) / sum(notebook_create_total) or vector(0)",
       "legendFormat": "Failure"
      }
     ]
    },
    {
     "title": "Notebook Container Creation Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_notebook_name!=\"\"}) by (label_notebook_name, pod, namespace) * on(pod, namespace) group_right() count(kube_pod_container_status_waiting_reason{reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff\"} == 1) by(reason, pod, namespace)",
       "legendFormat": "{{namespace}}-{{pod}} ({{reason}})"
      }
     ]
    },
    {
     "title": "OOMKilled Notebook Controller Pods",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() kube_pod_container_status_terminated_reason",
       "legendFormat": "{pod}} ({{reason}})"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() kube_pod_container_status_terminated_reason",
       "legendFormat": "{pod}} ({{reason}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines (Go)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_goroutines",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_goroutines",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Duration Quantile (Go)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() sum(go_gc_duration_seconds) by (pod) * 1000",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() sum(go_gc_duration_seconds) by (pod) * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation (Go)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() irate(go_memstats_alloc_bytes_total[1m])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() irate(go_memstats_alloc_bytes_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated (Go)",
     "type": "graph",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() irate(go_memstats_mallocs_total[1m])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() irate(go_memstats_mallocs_total[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notebook Controller Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() sum(container_memory_rss) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() sum(container_memory_rss) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Notebook Controller CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "lengthm" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() (sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)) * 1000",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() (sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)) * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Notebook Controller Memory in Stack (Kubeflow)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_stack_inuse_bytes",
       "legendFormat": "go_memstats_stack_inuse_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_stack_sys_bytes",
       "legendFormat": "go_memstats_stack_sys_bytes"
      }
     ]
    },
    {
     "title": "Notebook Controller Memory in Heap (Kubeflow)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_sys_bytes",
       "legendFormat": "go_memstats_heap_sys_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_inuse_bytes",
       "legendFormat": "go_memstats_heap_inuse_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_alloc_bytes",
       "legendFormat": "go_memstats_heap_alloc_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_idle_bytes",
       "legendFormat": "go_memstats_heap_idle_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_released_bytes",
       "legendFormat": "go_memstats_heap_released_bytes"
      }
     ]
    },
    {
     "title": "Notebook Controller Memory in Stack (Openshift)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_stack_inuse_bytes",
       "legendFormat": "go_memstats_stack_inuse_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_stack_sys_bytes",
       "legendFormat": "go_memstats_stack_sys_bytes"
      }
     ]
    },
    {
     "title": "Notebook Controller Memory in Heap (Openshift)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_sys_bytes",
       "legendFormat": "go_memstats_heap_sys_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_idle_bytes",
       "legendFormat": "go_memstats_heap_idle_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_alloc_bytes",
       "legendFormat": "go_memstats_heap_alloc_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_inuse_bytes",
       "legendFormat": "go_memstats_heap_inuse_bytes"
      },
      {
       "expr": "group(kube_pod_labels{label_app=\"openshift-notebook-controller\", namespace=~\"$namespace\"}) by (pod) * on(pod) group_right() go_memstats_heap_released_bytes",
       "legendFormat": "go_memstats_heap_released_bytes"
      }
     ]
    }
   ]
  }
 ]
}