---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: openshift-notebook-controller-webhook-cert
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
