apiVersion: v1
kind: Service
metadata:
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  name: service
spec:
  ports:
    - name: nbc-metrics
      port: 8080
  selector:
    app: notebook-controller
    kustomize.component: notebook-controller
